// Formats objects for setting up the Quill editor
export const formats = [
    "header",
    "font",
    "size",
    "bold",
    "italic",
    "underline",
    "align",
    "strike",
    "script",
    "blockquote",
    "background",
    "list",
    "indent",
    "link",
    "image",
    "color",
    "code-block",
];
// Kannada Labels for Icons
export const ICON_LABELS_KANNADA = {
    open: "ತೆರೆ",
    save: "ಉಳಿಸು",
    undo: "ರದ್ದು ಮಾಡು",
    redo: "ಮರುಕಳಿಸು",
    bold: "ದಪ್ಪ",
    italic: "ಚಕಟ್ಟಾದ",
    underline: "ಕೆಳಗೆ ಗೆರೆ ಎಳೆ",
    strike: "ಚುಕ್ಕು",
    listOrdered: "ಕ್ರಮಬದ್ಧ ಪಟ್ಟಿ",
    listBullet: "ಅಕ್ರಮ ಪಟ್ಟಿ",
    indentIncrease: "ಅಂತರ ಹೆಚ್ಚಿಸು",
    indentDecrease: "ಅಂತರ ಕಡಿಮೆಮಾಡು",
    superscript: "ಮೇಲ್ಬರಹ",
    subscript: "ಕೇಳಬರಹ",
    blockquote: "ಬ್ಲಾಕ್ ಕೋಟ್",
    direction: "ನಿರ್ದೇಶನ",
    align: "ಜೋಡಿಸು",
    color: "ಅಕ್ಷರದ ಬಣ್ಣ",
    background: "ಹಿನ್ನೆಲೆ ಬಣ್ಣ",
    link: "ಕೊಂಡಿ",
    image: "ಚಿತ್ರ",
    video: "ವೀಡಿಯೋ",
    formula: "ಸೂತ್ರ",
    codeBlock: "ಕೋಡ್ ಬ್ಲಾಕ್",
    clean: "ಸ್ವಚ್ಛಗೆ",
    font: "ಅಕ್ಷರದ ಪ್ರಕಾರ",
    fontSize: "ಅಕ್ಷರದ ಗಾತ್ರ",
    headline: "ಶೀರ್ಷಿಕೆ ಗಾತ್ರ",
    block:"ಕೋಡ್ ಬ್ಲಾಕ್"
};