name: Build Windows Artifact and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write  # Required for creating a release

jobs:
  build:

    runs-on: windows-latest  # Runs on Windows

    steps:
    - uses: actions/checkout@v4  # Checkout the repository

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: pwsh

    - name: Build Windows executable
      run: |
        python build_win.py  # Run the build_win.py script to create the artifact
      shell: pwsh

    - name: Create GitHub Release and upload artifact
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/kannadaNudi/kannadaNudi.zip  # Path to the zip file created by build_win.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
