name: Build and Release Kannada Nudi Editor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Required for creating a release

jobs:
  setup:
    name: Setup Environment
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: pwsh

  build:
    name: Build Windows Executable
    runs-on: windows-latest
    needs: setup  # Wait for setup job to complete

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build Windows Artifact
      run: |
        python build_win.py  # Run the script to generate the executable
      shell: pwsh

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: kannadaNudi-build
        path: dist/kannadaNudi/kannadaNudi.zip  # Upload the generated zip file

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest  # Running this on Ubuntu since it's just uploading
    needs: build  # Wait for the build job to complete

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: kannadaNudi-build
        path: dist/kannadaNudi/

    - name: Create GitHub Release and Upload Artifact
      uses: softprops/action-gh-release@v1
      with:
        files: dist/kannadaNudi/kannadaNudi.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
